services:
  - type: web
    name: pro-singapore
    env: node
    plan: free
    buildCommand: corepack enable && corepack prepare pnpm@9.15.9 --activate && pnpm install --frozen-lockfile && pnpm run build
    startCommand: node .next/standalone/server.js
    autoDeploy: true
    cacheDirectories:
      - .next/cache
      - .pnpm-store
