services:
  - type: web
    name: pro-singapore
    rootDir: .
    env: node
    plan: free
    buildCommand: corepack enable && corepack prepare pnpm@9.15.9 --activate && pnpm install --frozen-lockfile && CI= pnpm build
    startCommand: corepack pnpm start
    autoDeploy: true
    cacheDirectories:
      - .next/cache
      - .pnpm-store
